import Link from "next/link";
import { getSession } from "@/auth/session";
import { AdminShell } from "@/components/admin-shell";
import { env } from "@/config/env";
import { listProviderApplications } from "@/features/providers/api";
import { requireManagementResult } from "@/features/management-api";
import { StatusBadge } from "@/features/status-badge";
import { redirect } from "next/navigation";

const statuses = ["", "unverified", "under_review", "approved", "rejected", "resubmission_requested"];

export default async function ProvidersPage({ searchParams }: { searchParams: Promise<{ search?: string; status?: string; cursor?: string }> }) {
  const session = await getSession();
  if (session.state !== "authenticated") redirect("/login?reason=expired");
  const params = await searchParams;
  const page = await requireManagementResult(await listProviderApplications(params.search, params.status, params.cursor));
  return <AdminShell environment={env.appEnvironment} roles={session.session.roles} current="Providers"><header className="border-b border-[var(--color-border-default)] pb-6"><p className="m-0 text-sm font-semibold text-[var(--color-primary)]">Trust operations</p><h1 className="mt-2 mb-0 text-3xl font-bold">Provider verification</h1><p className="mt-2 mb-0 text-[var(--color-text-secondary)]">Review applications through assigned, auditable workflows.</p></header><form role="search" className="mt-6 grid gap-3 sm:grid-cols-[1fr_15rem_auto]"><label htmlFor="provider-search" className="sr-only">Search application or provider ID</label><input id="provider-search" name="search" defaultValue={params.search} placeholder="Application or provider ID" className="min-h-12 rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-secondary)] px-4"/><label htmlFor="status" className="sr-only">Status</label><select id="status" name="status" defaultValue={params.status ?? ""} className="min-h-12 rounded-xl border border-[var(--color-border-default)] bg-[var(--color-surface-secondary)] px-4">{statuses.map((status) => <option key={status} value={status}>{status ? status.replaceAll("_", " ") : "All statuses"}</option>)}</select><button className="min-h-12 rounded-xl bg-[var(--color-primary)] px-5 text-sm font-semibold text-[var(--color-on-primary)]">Filter</button></form><section aria-label="Provider application results" className="mt-6 grid gap-4">{page.items.length === 0 ? <article className="rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] p-6"><h2 className="m-0 text-lg font-semibold">No applications found</h2><p className="mt-2 mb-0 text-[var(--color-text-secondary)]">Adjust the filters and try again.</p></article> : page.items.map((application) => <article key={application.id} className="rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="m-0 text-lg font-semibold">{application.displayName ?? "Profile name unavailable"}</h2><p className="mt-1 mb-0 break-all font-mono text-xs text-[var(--color-text-muted)]">{application.id}</p></div><StatusBadge status={application.status}/></div><div className="mt-4 flex items-center justify-between gap-4"><p className="m-0 text-sm text-[var(--color-text-secondary)]">Updated {new Date(application.updatedAt).toLocaleString()}</p><Link className="font-semibold text-[var(--color-primary)]" href={`/providers/${application.id}`}>Open review</Link></div></article>)}{page.nextCursor ? <Link className="inline-flex min-h-11 w-fit items-center rounded-xl border border-[var(--color-border-strong)] px-4 font-semibold" href={{ pathname: "/providers", query: { search: params.search, status: params.status, cursor: page.nextCursor } }}>Next page</Link> : null}</section></AdminShell>;
}
