import { getSession } from "@/auth/session";
import { AdminShell } from "@/components/admin-shell";
import { env } from "@/config/env";
import { requireManagementResult } from "@/features/management-api";
import { getAnalytics } from "@/features/operations/api";
import Link from "next/link";
import { redirect } from "next/navigation";

function MetricCard({ label, value, detail, tone = "primary" }: { label: string; value: number; detail: string; tone?: "primary" | "success" | "warning" | "danger" }) {
  const colors = { primary: "border-[var(--color-primary)] text-[var(--color-primary)]", success: "border-emerald-400 text-emerald-300", warning: "border-[var(--color-warning)] text-[var(--color-warning)]", danger: "border-[var(--color-danger)] text-[var(--color-danger)]" } as const;
  return <article className="rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] p-5 shadow-[0_12px_28px_rgba(0,0,0,0.12)]"><p className="m-0 text-sm font-medium text-[var(--color-text-secondary)]">{label}</p><p className={`mt-3 mb-1 border-l-2 pl-3 text-3xl font-bold ${colors[tone]}`}>{value}</p><p className="m-0 text-sm text-[var(--color-text-muted)]">{detail}</p></article>;
}

export default async function Home() {
  const result = await getSession();
  if (result.state !== "authenticated") {
    if (result.state === "anonymous") redirect("/login");
    if (result.state === "expired") redirect("/login?reason=expired");
    redirect("/unauthorized");
  }
  const canViewAnalytics = result.session.roles.some((role) => role === "operations_administrator" || role === "auditor");
  const analytics = canViewAnalytics ? await requireManagementResult(await getAnalytics()) : null;
  const canManageBookings = result.session.roles.some((role) => ["support_agent", "trust_safety_reviewer", "operations_administrator", "auditor"].includes(role));
  const canManageSupport = canManageBookings;
  return <AdminShell environment={env.appEnvironment} roles={result.session.roles}>
    <header className="border-b border-[var(--color-border-default)] pb-6"><p className="m-0 text-sm font-semibold uppercase tracking-[0.08em] text-[var(--color-primary)]">FixNow operations</p><h1 className="mt-2 mb-0 text-3xl font-bold tracking-tight sm:text-[2.5rem]">Operations overview</h1><p className="mt-2 mb-0 max-w-2xl text-[var(--color-text-secondary)]">A focused view of the operational data available to your staff role.</p></header>
    {analytics ? <><section aria-labelledby="booking-health-heading" className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="m-0 text-sm font-semibold uppercase tracking-[0.08em] text-[var(--color-primary)]">Live operational picture</p><h2 id="booking-health-heading" className="mt-1 mb-0 text-xl font-semibold">Booking health</h2></div><Link className="font-semibold text-[var(--color-primary)]" href="/bookings">View bookings</Link></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total bookings" value={analytics.bookings.total} detail="All recorded bookings"/><MetricCard label="Requested or active" value={analytics.bookings.pending} detail="Needs operational attention" tone="warning"/><MetricCard label="Completed" value={analytics.bookings.completed} detail="Completed bookings" tone="success"/><MetricCard label="Cancelled" value={analytics.bookings.cancelled} detail="Cancelled bookings" tone="danger"/></div></section><section aria-labelledby="provider-health-heading" className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="m-0 text-sm font-semibold uppercase tracking-[0.08em] text-[var(--color-primary)]">Network readiness</p><h2 id="provider-health-heading" className="mt-1 mb-0 text-xl font-semibold">Provider health</h2></div><Link className="font-semibold text-[var(--color-primary)]" href="/providers">Review providers</Link></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Providers" value={analytics.providers.total} detail="Provider accounts in the network"/><MetricCard label="Online now" value={analytics.providers.active} detail="Currently active providers" tone="success"/><MetricCard label="Verified" value={analytics.providers.verified} detail="Approved provider accounts" tone="success"/><MetricCard label="Pending review" value={analytics.providers.pendingVerification} detail="Verification applications awaiting review" tone="warning"/></div></section></> : <section aria-labelledby="access-heading" className="mt-8 rounded-3xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] p-6"><p className="m-0 text-sm font-semibold uppercase tracking-[0.08em] text-[var(--color-primary)]">Your access</p><h2 id="access-heading" className="mt-2 mb-0 text-xl font-semibold">Choose an operation from the navigation</h2><p className="mt-2 mb-0 max-w-2xl text-[var(--color-text-secondary)]">Your role does not include platform-wide analytics. Use the available workspace modules to manage the operations assigned to you.</p></section>}
    {(canManageBookings || canManageSupport) ? <section aria-labelledby="next-actions-heading" className="mt-8"><h2 id="next-actions-heading" className="m-0 text-xl font-semibold">Quick actions</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{canManageBookings ? <Link href="/bookings" className="rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] p-5 transition hover:border-[var(--color-primary)] hover:bg-[var(--color-surface-elevated)]"><p className="m-0 text-lg font-semibold">Inspect bookings</p><p className="mt-2 mb-0 text-sm text-[var(--color-text-secondary)]">Find a request, check its status, and open its operational record.</p></Link> : null}{canManageSupport ? <Link href="/support" className="rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-primary)] p-5 transition hover:border-[var(--color-primary)] hover:bg-[var(--color-surface-elevated)]"><p className="m-0 text-lg font-semibold">Review support cases</p><p className="mt-2 mb-0 text-sm text-[var(--color-text-secondary)]">Manage reported concerns using the case workflow.</p></Link> : null}</div></section> : null}
  </AdminShell>;
}
