import { MigrationInterface, QueryRunner } from "typeorm";

export class BookingModel1786519799533 implements MigrationInterface {
    name = 'BookingModel1786519799533'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "auth_audit_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "event_type" character varying(60) NOT NULL, "outcome" character varying(20) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4ce7e89f8c00d8b6a81408713f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "otp_challenges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "identity_id" uuid NOT NULL, "code_hash" character(64) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "resend_after" TIMESTAMP WITH TIME ZONE NOT NULL, "attempts_remaining" smallint NOT NULL DEFAULT '5', "consumed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c34f21df6c8aa51229715452068" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auth_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_family_id" uuid NOT NULL, "refresh_token_hash" character(64) NOT NULL, "role" character varying(40) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, "revoke_reason" character varying(40), "replaced_by_session_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8ae45196f82be4540770b41ac50" UNIQUE ("refresh_token_hash"), CONSTRAINT "PK_641507381f32580e8479efc36cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('REQUESTED', 'ASSIGNED', 'EN_ROUTE', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid NOT NULL, "providerId" uuid, "serviceCategoryId" uuid NOT NULL, "status" "public"."bookings_status_enum" NOT NULL DEFAULT 'REQUESTED', "description" text NOT NULL, "locationLat" numeric(10,7) NOT NULL, "locationLng" numeric(10,7) NOT NULL, "scheduledAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."account_status" AS ENUM('pending_verification', 'active', 'restricted', 'suspended', 'deactivated', 'deletion_pending', 'deleted_anonymized')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."account_status" NOT NULL DEFAULT 'pending_verification', "status_reason" character varying(255), "status_changed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "provider_availability" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "time_zone" character varying(100) NOT NULL, "weekly_rules" jsonb NOT NULL DEFAULT '[]'::jsonb, "exceptions" jsonb NOT NULL DEFAULT '[]'::jsonb, "status" character varying(16) NOT NULL DEFAULT 'offline', "status_expires_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_490189d647c5573e6c5f7a37176" UNIQUE ("user_id"), CONSTRAINT "REL_490189d647c5573e6c5f7a3717" UNIQUE ("user_id"), CONSTRAINT "PK_b71cd0a5d4be0a7c6851c51a7b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "provider_document_audit_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "actor_user_id" uuid NOT NULL, "action" character varying(30) NOT NULL, "outcome" character varying(20) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fa876845fd1fcf2a4cabd07afae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "provider_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "document_type" character varying(40) NOT NULL, "object_key" character varying(160) NOT NULL, "content_type" character varying(80) NOT NULL, "size_bytes" integer NOT NULL, "sha256" character(64) NOT NULL, "status" character varying(20) NOT NULL, "retention_until" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_7a60af890d6b911946572042794" UNIQUE ("object_key"), CONSTRAINT "PK_bc3bb226a18aa1bbae0baa7df15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."provider_onboarding_status" AS ENUM('unverified', 'under_review', 'approved', 'rejected', 'resubmission_requested')`);
        await queryRunner.query(`CREATE TABLE "provider_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "status" "public"."provider_onboarding_status" NOT NULL DEFAULT 'unverified', "assigned_reviewer_user_id" uuid, "decision_reason" character varying(1000), "reviewed_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_eba05ee9702912bfa7c2a5267da" UNIQUE ("user_id"), CONSTRAINT "REL_eba05ee9702912bfa7c2a5267d" UNIQUE ("user_id"), CONSTRAINT "PK_4262a1be4435ab71d0795cb8d19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "provider_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "display_name" character varying(120) NOT NULL, "bio" character varying(1000), "service_radius_km" double precision NOT NULL, "base_latitude" double precision NOT NULL, "base_longitude" double precision NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_5d1880ed16ff13ea6fd9bca019d" UNIQUE ("user_id"), CONSTRAINT "REL_5d1880ed16ff13ea6fd9bca019" UNIQUE ("user_id"), CONSTRAINT "PK_0197ced76e32133df96a97168df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "provider_verification_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "application_id" uuid NOT NULL, "actor_user_id" uuid NOT NULL, "from_status" character varying(40) NOT NULL, "to_status" character varying(40) NOT NULL, "reason" character varying(1000) NOT NULL, "application_version" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_dbdceff17d6caba9c68dee54e98" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text, "icon_name" character varying(100), "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "is_emergency" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_7ef2e28b495d09a4eb28997c653" UNIQUE ("name"), CONSTRAINT "UQ_88a33271b3d94a0c4bc14db3b76" UNIQUE ("slug"), CONSTRAINT "PK_fe4da5476c4ffe5aa2d3524ae68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "provider_skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "service_category_id" uuid NOT NULL, "years_experience" integer, "hourly_rate_cents" integer, "visit_fee_cents" integer, "description" text, "is_verified" boolean NOT NULL DEFAULT false, "verification_notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_45e16127623ec2780b132dda619" UNIQUE ("user_id", "service_category_id"), CONSTRAINT "PK_e9dd51014ef22fc9c5862b6fe77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_identities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "provider" character varying(64) NOT NULL, "subject" character varying(255) NOT NULL, "verified_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_user_identities_provider_subject" UNIQUE ("provider", "subject"), CONSTRAINT "PK_e23bff04e9c3e7b785e442b262c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auth_credentials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "identity_id" uuid NOT NULL, "password_hash" character varying(512) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_4e1b069a0f34d34fb08cef28bb3" UNIQUE ("identity_id"), CONSTRAINT "REL_4e1b069a0f34d34fb08cef28bb" UNIQUE ("identity_id"), CONSTRAINT "PK_90fdced0865b5f15586e7cd3b25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customer_profiles" ("user_id" uuid NOT NULL, "display_name" character varying(80) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_99617dd6d452ad43dd992a79933" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(80) NOT NULL, "description" character varying(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_roles_code" UNIQUE ("code"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, "assigned_by_user_id" uuid, "reason" character varying(255) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_user_roles_user_role" UNIQUE ("user_id", "role_id"), CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ADD CONSTRAINT "FK_490189d647c5573e6c5f7a37176" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_applications" ADD CONSTRAINT "FK_eba05ee9702912bfa7c2a5267da" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "FK_5d1880ed16ff13ea6fd9bca019d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_skills" ADD CONSTRAINT "FK_b361a76e0166a51459c05d7e20a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_skills" ADD CONSTRAINT "FK_38ba9241199339a0c50796fb184" FOREIGN KEY ("service_category_id") REFERENCES "service_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_identities" ADD CONSTRAINT "FK_bf5fe01eb8cad7114b4c371cdc7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" ADD CONSTRAINT "FK_4e1b069a0f34d34fb08cef28bb3" FOREIGN KEY ("identity_id") REFERENCES "user_identities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" ADD CONSTRAINT "FK_99617dd6d452ad43dd992a79933" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" DROP CONSTRAINT "FK_99617dd6d452ad43dd992a79933"`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" DROP CONSTRAINT "FK_4e1b069a0f34d34fb08cef28bb3"`);
        await queryRunner.query(`ALTER TABLE "user_identities" DROP CONSTRAINT "FK_bf5fe01eb8cad7114b4c371cdc7"`);
        await queryRunner.query(`ALTER TABLE "provider_skills" DROP CONSTRAINT "FK_38ba9241199339a0c50796fb184"`);
        await queryRunner.query(`ALTER TABLE "provider_skills" DROP CONSTRAINT "FK_b361a76e0166a51459c05d7e20a"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "FK_5d1880ed16ff13ea6fd9bca019d"`);
        await queryRunner.query(`ALTER TABLE "provider_applications" DROP CONSTRAINT "FK_eba05ee9702912bfa7c2a5267da"`);
        await queryRunner.query(`ALTER TABLE "provider_availability" DROP CONSTRAINT "FK_490189d647c5573e6c5f7a37176"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "customer_profiles"`);
        await queryRunner.query(`DROP TABLE "auth_credentials"`);
        await queryRunner.query(`DROP TABLE "user_identities"`);
        await queryRunner.query(`DROP TABLE "provider_skills"`);
        await queryRunner.query(`DROP TABLE "service_categories"`);
        await queryRunner.query(`DROP TABLE "provider_verification_events"`);
        await queryRunner.query(`DROP TABLE "provider_profiles"`);
        await queryRunner.query(`DROP TABLE "provider_applications"`);
        await queryRunner.query(`DROP TYPE "public"."provider_onboarding_status"`);
        await queryRunner.query(`DROP TABLE "provider_documents"`);
        await queryRunner.query(`DROP TABLE "provider_document_audit_events"`);
        await queryRunner.query(`DROP TABLE "provider_availability"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."account_status"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`DROP TABLE "auth_sessions"`);
        await queryRunner.query(`DROP TABLE "otp_challenges"`);
        await queryRunner.query(`DROP TABLE "auth_audit_events"`);
    }

}
