import { MigrationInterface, QueryRunner } from "typeorm";

export class CheckSchemaSync1789749968260 implements MigrationInterface {
    name = 'CheckSchemaSync1789749968260'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "auth_audit_events" DROP CONSTRAINT "fk_auth_audit_events_user"`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" DROP CONSTRAINT "fk_auth_sessions_user"`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" DROP CONSTRAINT "fk_otp_challenges_identity"`);
        await queryRunner.query(`ALTER TABLE "provider_skills" DROP CONSTRAINT "FK_provider_skills_user"`);
        await queryRunner.query(`ALTER TABLE "provider_skills" DROP CONSTRAINT "FK_provider_skills_service_category"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_customer"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_provider"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_bookings_category"`);
        await queryRunner.query(`ALTER TABLE "booking_calls" DROP CONSTRAINT "FK_booking_calls_booking"`);
        await queryRunner.query(`ALTER TABLE "booking_calls" DROP CONSTRAINT "FK_booking_calls_caller"`);
        await queryRunner.query(`ALTER TABLE "booking_calls" DROP CONSTRAINT "FK_booking_calls_callee"`);
        await queryRunner.query(`ALTER TABLE "booking_events" DROP CONSTRAINT "FK_booking_events_booking"`);
        await queryRunner.query(`ALTER TABLE "booking_events" DROP CONSTRAINT "FK_booking_events_actor"`);
        await queryRunner.query(`ALTER TABLE "booking_messages" DROP CONSTRAINT "FK_booking_messages_booking"`);
        await queryRunner.query(`ALTER TABLE "booking_messages" DROP CONSTRAINT "FK_booking_messages_sender"`);
        await queryRunner.query(`ALTER TABLE "emergency_dispatches" DROP CONSTRAINT "FK_emergency_dispatches_booking"`);
        await queryRunner.query(`ALTER TABLE "push_device_tokens" DROP CONSTRAINT "FK_push_device_tokens_user"`);
        await queryRunner.query(`ALTER TABLE "provider_availability" DROP CONSTRAINT "FK_provider_availability_user"`);
        await queryRunner.query(`ALTER TABLE "provider_document_audit_events" DROP CONSTRAINT "FK_provider_document_audit_document"`);
        await queryRunner.query(`ALTER TABLE "provider_documents" DROP CONSTRAINT "FK_provider_documents_user"`);
        await queryRunner.query(`ALTER TABLE "provider_applications" DROP CONSTRAINT "fk_provider_applications_user"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "FK_provider_profiles_user"`);
        await queryRunner.query(`ALTER TABLE "provider_verification_events" DROP CONSTRAINT "FK_provider_verification_application"`);
        await queryRunner.query(`ALTER TABLE "review_moderation_events" DROP CONSTRAINT "FK_review_moderation_events_review"`);
        await queryRunner.query(`ALTER TABLE "review_moderation_events" DROP CONSTRAINT "FK_review_moderation_events_actor"`);
        await queryRunner.query(`ALTER TABLE "booking_reviews" DROP CONSTRAINT "FK_booking_reviews_booking"`);
        await queryRunner.query(`ALTER TABLE "booking_reviews" DROP CONSTRAINT "FK_booking_reviews_customer"`);
        await queryRunner.query(`ALTER TABLE "booking_reviews" DROP CONSTRAINT "FK_booking_reviews_provider"`);
        await queryRunner.query(`ALTER TABLE "trust_signals" DROP CONSTRAINT "FK_trust_signals_reviewer"`);
        await queryRunner.query(`ALTER TABLE "user_identities" DROP CONSTRAINT "fk_user_identities_user"`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" DROP CONSTRAINT "fk_auth_credentials_identity"`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" DROP CONSTRAINT "fk_customer_profiles_user"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "fk_user_roles_user"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "fk_user_roles_role"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "fk_user_roles_assigner"`);
        await queryRunner.query(`ALTER TABLE "complaint_evidence" DROP CONSTRAINT "FK_complaint_evidence_complaint"`);
        await queryRunner.query(`ALTER TABLE "complaint_evidence" DROP CONSTRAINT "FK_complaint_evidence_uploader"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_complaints_booking"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_complaints_submitter"`);
        await queryRunner.query(`ALTER TABLE "complaint_audits" DROP CONSTRAINT "FK_complaint_audits_complaint"`);
        await queryRunner.query(`ALTER TABLE "complaint_audits" DROP CONSTRAINT "FK_complaint_audits_actor"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_sessions_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_auth_sessions_family_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_otp_challenges_identity_created"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_provider_skills_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_provider_skills_service_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_provider_skills_is_verified"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_service_categories_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_service_categories_display_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_service_categories_is_emergency"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_customer_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_provider_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bookings_matching"`);
        await queryRunner.query(`DROP INDEX "public"."IX_booking_calls_booking"`);
        await queryRunner.query(`DROP INDEX "public"."IX_booking_calls_caller"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_booking_events_booking"`);
        await queryRunner.query(`DROP INDEX "public"."IX_booking_messages_booking_created"`);
        await queryRunner.query(`DROP INDEX "public"."IX_booking_messages_sender"`);
        await queryRunner.query(`DROP INDEX "public"."IX_emergency_dispatches_wave"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_push_device_tokens_user"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_invoices_order"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_invoices_number"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_payment_orders_gateway_order"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_payment_orders_receipt"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_refunds_gateway"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_refunds_request_key"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_review_photos_object_key"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_booking_reviews_provider_published"`);
        await queryRunner.query(`DROP INDEX "public"."ix_user_identities_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_user_roles_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_user_roles_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."IX_complaint_evidence_complaint"`);
        await queryRunner.query(`DROP INDEX "public"."IX_complaints_status"`);
        await queryRunner.query(`DROP INDEX "public"."IX_complaints_submitter"`);
        await queryRunner.query(`DROP INDEX "public"."IX_complaints_booking"`);
        await queryRunner.query(`DROP INDEX "public"."IX_complaints_assignee"`);
        await queryRunner.query(`DROP INDEX "public"."IX_complaint_audits_complaint"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "CHK_bookings_latitude"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "CHK_bookings_longitude"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "CHK_bookings_description"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "CHK_bookings_cancellation"`);
        await queryRunner.query(`ALTER TABLE "recurring_schedules" DROP CONSTRAINT "CHK_recurring_schedules_cadence"`);
        await queryRunner.query(`ALTER TABLE "recurring_schedules" DROP CONSTRAINT "CHK_recurring_schedules_status"`);
        await queryRunner.query(`ALTER TABLE "emergency_dispatches" DROP CONSTRAINT "CHK_emergency_wave_range"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "CHK_notification_deliveries_status"`);
        await queryRunner.query(`ALTER TABLE "provider_availability" DROP CONSTRAINT "CHK_provider_availability_status"`);
        await queryRunner.query(`ALTER TABLE "provider_availability" DROP CONSTRAINT "CHK_provider_availability_status_expiry"`);
        await queryRunner.query(`ALTER TABLE "provider_documents" DROP CONSTRAINT "provider_documents_size_bytes_check"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "CHK_provider_profiles_radius"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "CHK_provider_profiles_latitude"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "CHK_provider_profiles_longitude"`);
        await queryRunner.query(`ALTER TABLE "booking_reviews" DROP CONSTRAINT "CHK_booking_reviews_text"`);
        await queryRunner.query(`ALTER TABLE "provider_skills" DROP CONSTRAINT "UQ_provider_skills_user_service"`);
        await queryRunner.query(`CREATE TYPE "public"."guarantee_claims_status_enum" AS ENUM('PENDING', 'IN_REVIEW', 'MORE_INFO', 'APPROVED', 'REJECTED', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "guarantee_claims" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "original_provider_id" uuid, "status" "public"."guarantee_claims_status_enum" NOT NULL DEFAULT 'PENDING', "description" text NOT NULL, "evidence_urls" text, "admin_notes" text, "assigned_provider_id" uuid, "re_service_booking_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_84abb9e309fb6ac575527a96fa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."appeal_status" AS ENUM('NONE', 'PENDING', 'GRANTED', 'DENIED')`);
        await queryRunner.query(`ALTER TABLE "trust_signals" ADD "appealStatus" "public"."appeal_status" NOT NULL DEFAULT 'NONE'`);
        await queryRunner.query(`ALTER TABLE "trust_signals" ADD "appeal_reason" text`);
        await queryRunner.query(`ALTER TABLE "trust_signals" ADD "appeal_resolution" text`);
        await queryRunner.query(`ALTER TABLE "auth_audit_events" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status_changed_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."push_platform" RENAME TO "push_platform_old"`);
        await queryRunner.query(`CREATE TYPE "public"."push_device_tokens_platform_enum" AS ENUM('ANDROID', 'IOS', 'WEB')`);
        await queryRunner.query(`ALTER TABLE "push_device_tokens" ALTER COLUMN "platform" TYPE "public"."push_device_tokens_platform_enum" USING "platform"::"text"::"public"."push_device_tokens_platform_enum"`);
        await queryRunner.query(`DROP TYPE "public"."push_platform_old"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "issued_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payment_orders" DROP CONSTRAINT "CHK_payment_orders_status"`);
        await queryRunner.query(`ALTER TABLE "payment_orders" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "payment_orders" ADD "status" character varying NOT NULL DEFAULT 'CREATED'`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "CHK_refunds_status"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD "status" character varying NOT NULL DEFAULT 'PROCESSED'`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ALTER COLUMN "weekly_rules" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ALTER COLUMN "exceptions" SET DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "provider_applications" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "provider_applications" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "review_photos" DROP CONSTRAINT "CHK_review_photos_status"`);
        await queryRunner.query(`ALTER TABLE "review_photos" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "review_photos" ADD "status" character varying NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "booking_reviews" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "trust_signals" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user_identities" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "complaints" ALTER COLUMN "version" DROP DEFAULT`);
        await queryRunner.query(`CREATE INDEX "IDX_6e59be68a9d84d799895fb0158" ON "push_device_tokens"  ("user_id") `);
        await queryRunner.query(`ALTER TABLE "payment_orders" ADD CONSTRAINT "CHK_payment_orders_status" CHECK (status IN ('CREATED', 'PAID', 'FAILED', 'CANCELLED'))`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "CHK_refunds_status" CHECK (status IN ('PENDING', 'PROCESSED'))`);
        await queryRunner.query(`ALTER TABLE "review_photos" ADD CONSTRAINT "CHK_review_photos_status" CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))`);
        await queryRunner.query(`ALTER TABLE "provider_skills" ADD CONSTRAINT "UQ_45e16127623ec2780b132dda619" UNIQUE ("user_id", "service_category_id")`);
        await queryRunner.query(`ALTER TABLE "provider_skills" ADD CONSTRAINT "FK_b361a76e0166a51459c05d7e20a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_skills" ADD CONSTRAINT "FK_38ba9241199339a0c50796fb184" FOREIGN KEY ("service_category_id") REFERENCES "service_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_line_items" ADD CONSTRAINT "FK_324fa1ce9caaf5ce1944383d128" FOREIGN KEY ("sub_service_id") REFERENCES "sub_services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_calls" ADD CONSTRAINT "FK_ec8b1e1f91e367814e4ca6b59b4" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_events" ADD CONSTRAINT "FK_f71c073e8e26aca6917ea146c80" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_messages" ADD CONSTRAINT "FK_74665ddf44ef82a474462f22100" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emergency_dispatches" ADD CONSTRAINT "FK_d83d98d0732a2a5a3b446966b73" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_device_tokens" ADD CONSTRAINT "FK_6e59be68a9d84d799895fb01588" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ADD CONSTRAINT "FK_490189d647c5573e6c5f7a37176" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_applications" ADD CONSTRAINT "FK_eba05ee9702912bfa7c2a5267da" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "FK_5d1880ed16ff13ea6fd9bca019d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_identities" ADD CONSTRAINT "FK_bf5fe01eb8cad7114b4c371cdc7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" ADD CONSTRAINT "FK_4e1b069a0f34d34fb08cef28bb3" FOREIGN KEY ("identity_id") REFERENCES "user_identities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" ADD CONSTRAINT "FK_99617dd6d452ad43dd992a79933" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaint_evidence" ADD CONSTRAINT "FK_eac97711b486710cac095d6c436" FOREIGN KEY ("complaint_id") REFERENCES "complaints"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaint_audits" ADD CONSTRAINT "FK_5eb656f156f0e89755498939fb5" FOREIGN KEY ("complaint_id") REFERENCES "complaints"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "complaint_audits" DROP CONSTRAINT "FK_5eb656f156f0e89755498939fb5"`);
        await queryRunner.query(`ALTER TABLE "complaint_evidence" DROP CONSTRAINT "FK_eac97711b486710cac095d6c436"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" DROP CONSTRAINT "FK_99617dd6d452ad43dd992a79933"`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" DROP CONSTRAINT "FK_4e1b069a0f34d34fb08cef28bb3"`);
        await queryRunner.query(`ALTER TABLE "user_identities" DROP CONSTRAINT "FK_bf5fe01eb8cad7114b4c371cdc7"`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" DROP CONSTRAINT "FK_5d1880ed16ff13ea6fd9bca019d"`);
        await queryRunner.query(`ALTER TABLE "provider_applications" DROP CONSTRAINT "FK_eba05ee9702912bfa7c2a5267da"`);
        await queryRunner.query(`ALTER TABLE "provider_availability" DROP CONSTRAINT "FK_490189d647c5573e6c5f7a37176"`);
        await queryRunner.query(`ALTER TABLE "push_device_tokens" DROP CONSTRAINT "FK_6e59be68a9d84d799895fb01588"`);
        await queryRunner.query(`ALTER TABLE "emergency_dispatches" DROP CONSTRAINT "FK_d83d98d0732a2a5a3b446966b73"`);
        await queryRunner.query(`ALTER TABLE "booking_messages" DROP CONSTRAINT "FK_74665ddf44ef82a474462f22100"`);
        await queryRunner.query(`ALTER TABLE "booking_events" DROP CONSTRAINT "FK_f71c073e8e26aca6917ea146c80"`);
        await queryRunner.query(`ALTER TABLE "booking_calls" DROP CONSTRAINT "FK_ec8b1e1f91e367814e4ca6b59b4"`);
        await queryRunner.query(`ALTER TABLE "booking_line_items" DROP CONSTRAINT "FK_324fa1ce9caaf5ce1944383d128"`);
        await queryRunner.query(`ALTER TABLE "provider_skills" DROP CONSTRAINT "FK_38ba9241199339a0c50796fb184"`);
        await queryRunner.query(`ALTER TABLE "provider_skills" DROP CONSTRAINT "FK_b361a76e0166a51459c05d7e20a"`);
        await queryRunner.query(`ALTER TABLE "provider_skills" DROP CONSTRAINT "UQ_45e16127623ec2780b132dda619"`);
        await queryRunner.query(`ALTER TABLE "review_photos" DROP CONSTRAINT "CHK_review_photos_status"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "CHK_refunds_status"`);
        await queryRunner.query(`ALTER TABLE "payment_orders" DROP CONSTRAINT "CHK_payment_orders_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e59be68a9d84d799895fb0158"`);
        await queryRunner.query(`ALTER TABLE "complaints" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_identities" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "trust_signals" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "booking_reviews" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "review_photos" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "review_photos" ADD "status" character varying(16) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "review_photos" ADD CONSTRAINT "CHK_review_photos_status" CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "provider_applications" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "provider_applications" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ALTER COLUMN "exceptions" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ALTER COLUMN "weekly_rules" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD "status" character varying(16) NOT NULL DEFAULT 'PROCESSED'`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "CHK_refunds_status" CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "payment_orders" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "payment_orders" ADD "status" character varying(24) NOT NULL DEFAULT 'CREATED'`);
        await queryRunner.query(`ALTER TABLE "payment_orders" ADD CONSTRAINT "CHK_payment_orders_status" CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'PAID'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "issued_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."push_platform_old" AS ENUM('ANDROID', 'IOS', 'WEB')`);
        await queryRunner.query(`ALTER TABLE "push_device_tokens" ALTER COLUMN "platform" TYPE "public"."push_platform_old" USING "platform"::"text"::"public"."push_platform_old"`);
        await queryRunner.query(`DROP TYPE "public"."push_device_tokens_platform_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."push_platform_old" RENAME TO "push_platform"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "version" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status_changed_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "auth_audit_events" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "trust_signals" DROP COLUMN "appeal_resolution"`);
        await queryRunner.query(`ALTER TABLE "trust_signals" DROP COLUMN "appeal_reason"`);
        await queryRunner.query(`ALTER TABLE "trust_signals" DROP COLUMN "appealStatus"`);
        await queryRunner.query(`DROP TYPE "public"."appeal_status"`);
        await queryRunner.query(`DROP TABLE "guarantee_claims"`);
        await queryRunner.query(`DROP TYPE "public"."guarantee_claims_status_enum"`);
        await queryRunner.query(`ALTER TABLE "provider_skills" ADD CONSTRAINT "UQ_provider_skills_user_service" UNIQUE ("user_id", "service_category_id")`);
        await queryRunner.query(`ALTER TABLE "booking_reviews" ADD CONSTRAINT "CHK_booking_reviews_text" CHECK (((review_text IS NULL) OR ((length(btrim((review_text)::text)) >= 1) AND (length(btrim((review_text)::text)) <= 1000))))`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "CHK_provider_profiles_longitude" CHECK (((base_longitude >= ('-180'::integer)::double precision) AND (base_longitude <= (180)::double precision)))`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "CHK_provider_profiles_latitude" CHECK (((base_latitude >= ('-90'::integer)::double precision) AND (base_latitude <= (90)::double precision)))`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "CHK_provider_profiles_radius" CHECK (((service_radius_km >= (1)::double precision) AND (service_radius_km <= (100)::double precision)))`);
        await queryRunner.query(`ALTER TABLE "provider_documents" ADD CONSTRAINT "provider_documents_size_bytes_check" CHECK (((size_bytes > 0) AND (size_bytes <= 10485760)))`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ADD CONSTRAINT "CHK_provider_availability_status_expiry" CHECK (((((status)::text = 'offline'::text) AND (status_expires_at IS NULL)) OR (((status)::text = ANY ((ARRAY['online'::character varying, 'busy'::character varying])::text[])) AND (status_expires_at IS NOT NULL))))`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ADD CONSTRAINT "CHK_provider_availability_status" CHECK (((status)::text = ANY ((ARRAY['online'::character varying, 'busy'::character varying, 'offline'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "CHK_notification_deliveries_status" CHECK (((status)::text = ANY ((ARRAY['SENT'::character varying, 'FAILED'::character varying, 'NO_DEVICES'::character varying, 'SKIPPED_QUIET_HOURS'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "emergency_dispatches" ADD CONSTRAINT "CHK_emergency_wave_range" CHECK (((current_wave >= 0) AND (current_wave <= 3)))`);
        await queryRunner.query(`ALTER TABLE "recurring_schedules" ADD CONSTRAINT "CHK_recurring_schedules_status" CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PAUSED'::character varying, 'CANCELLED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "recurring_schedules" ADD CONSTRAINT "CHK_recurring_schedules_cadence" CHECK (((cadence)::text = ANY ((ARRAY['WEEKLY'::character varying, 'MONTHLY'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "CHK_bookings_cancellation" CHECK ((((status = 'CANCELLED'::booking_status) AND (cancellation_reason IS NOT NULL) AND (cancelled_at IS NOT NULL)) OR ((status <> 'CANCELLED'::booking_status) AND (cancellation_reason IS NULL) AND (cancelled_at IS NULL))))`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "CHK_bookings_description" CHECK (((length(btrim((description)::text)) >= 1) AND (length(btrim((description)::text)) <= 2000)))`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "CHK_bookings_longitude" CHECK (((location_lng >= ('-180'::integer)::numeric) AND (location_lng <= (180)::numeric)))`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "CHK_bookings_latitude" CHECK (((location_lat >= ('-90'::integer)::numeric) AND (location_lat <= (90)::numeric)))`);
        await queryRunner.query(`CREATE INDEX "IX_complaint_audits_complaint" ON "complaint_audits" USING btree ("complaint_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IX_complaints_assignee" ON "complaints" USING btree ("assignee_id") `);
        await queryRunner.query(`CREATE INDEX "IX_complaints_booking" ON "complaints" USING btree ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IX_complaints_submitter" ON "complaints" USING btree ("submitter_id") `);
        await queryRunner.query(`CREATE INDEX "IX_complaints_status" ON "complaints" USING btree ("created_at", "status") `);
        await queryRunner.query(`CREATE INDEX "IX_complaint_evidence_complaint" ON "complaint_evidence" USING btree ("complaint_id") `);
        await queryRunner.query(`CREATE INDEX "ix_user_roles_role_id" ON "user_roles" USING btree ("role_id") `);
        await queryRunner.query(`CREATE INDEX "ix_user_roles_user_id" ON "user_roles" USING btree ("user_id") `);
        await queryRunner.query(`CREATE INDEX "ix_user_identities_user_id" ON "user_identities" USING btree ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_booking_reviews_provider_published" ON "booking_reviews" USING btree ("created_at", "provider_id") WHERE (moderation_status = 'PUBLISHED'::review_moderation_status)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_review_photos_object_key" ON "review_photos" USING btree ("object_key") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_refunds_request_key" ON "refunds" USING btree ("request_key") WHERE (request_key IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_refunds_gateway" ON "refunds" USING btree ("gateway_refund_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_payment_orders_receipt" ON "payment_orders" USING btree ("receipt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_payment_orders_gateway_order" ON "payment_orders" USING btree ("gateway_order_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_invoices_number" ON "invoices" USING btree ("invoice_number") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_invoices_order" ON "invoices" USING btree ("payment_order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_push_device_tokens_user" ON "push_device_tokens" USING btree ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IX_emergency_dispatches_wave" ON "emergency_dispatches" USING btree ("current_wave") `);
        await queryRunner.query(`CREATE INDEX "IX_booking_messages_sender" ON "booking_messages" USING btree ("sender_user_id") `);
        await queryRunner.query(`CREATE INDEX "IX_booking_messages_booking_created" ON "booking_messages" USING btree ("booking_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_booking_events_booking" ON "booking_events" USING btree ("booking_id", "created_at", "id") `);
        await queryRunner.query(`CREATE INDEX "IX_booking_calls_caller" ON "booking_calls" USING btree ("caller_user_id") `);
        await queryRunner.query(`CREATE INDEX "IX_booking_calls_booking" ON "booking_calls" USING btree ("booking_id", "started_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_matching" ON "bookings" USING btree ("created_at", "service_category_id", "status") WHERE ((status = 'REQUESTED'::booking_status) AND (deleted_at IS NULL))`);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_provider_history" ON "bookings" USING btree ("created_at", "id", "provider_id") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_bookings_customer_history" ON "bookings" USING btree ("created_at", "customer_id", "id") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_service_categories_is_emergency" ON "service_categories" USING btree ("is_emergency") `);
        await queryRunner.query(`CREATE INDEX "IDX_service_categories_display_order" ON "service_categories" USING btree ("display_order") `);
        await queryRunner.query(`CREATE INDEX "IDX_service_categories_is_active" ON "service_categories" USING btree ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_provider_skills_is_verified" ON "provider_skills" USING btree ("is_verified") `);
        await queryRunner.query(`CREATE INDEX "IDX_provider_skills_service_category_id" ON "provider_skills" USING btree ("service_category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_provider_skills_user_id" ON "provider_skills" USING btree ("user_id") `);
        await queryRunner.query(`CREATE INDEX "ix_otp_challenges_identity_created" ON "otp_challenges" USING btree ("created_at", "identity_id") `);
        await queryRunner.query(`CREATE INDEX "ix_auth_sessions_family_id" ON "auth_sessions" USING btree ("token_family_id") `);
        await queryRunner.query(`CREATE INDEX "ix_auth_sessions_user_id" ON "auth_sessions" USING btree ("user_id") `);
        await queryRunner.query(`ALTER TABLE "complaint_audits" ADD CONSTRAINT "FK_complaint_audits_actor" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaint_audits" ADD CONSTRAINT "FK_complaint_audits_complaint" FOREIGN KEY ("complaint_id") REFERENCES "complaints"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_complaints_submitter" FOREIGN KEY ("submitter_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_complaints_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaint_evidence" ADD CONSTRAINT "FK_complaint_evidence_uploader" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaint_evidence" ADD CONSTRAINT "FK_complaint_evidence_complaint" FOREIGN KEY ("complaint_id") REFERENCES "complaints"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_assigner" FOREIGN KEY ("assigned_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" ADD CONSTRAINT "fk_customer_profiles_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" ADD CONSTRAINT "fk_auth_credentials_identity" FOREIGN KEY ("identity_id") REFERENCES "user_identities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_identities" ADD CONSTRAINT "fk_user_identities_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trust_signals" ADD CONSTRAINT "FK_trust_signals_reviewer" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_reviews" ADD CONSTRAINT "FK_booking_reviews_provider" FOREIGN KEY ("provider_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_reviews" ADD CONSTRAINT "FK_booking_reviews_customer" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_reviews" ADD CONSTRAINT "FK_booking_reviews_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review_moderation_events" ADD CONSTRAINT "FK_review_moderation_events_actor" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review_moderation_events" ADD CONSTRAINT "FK_review_moderation_events_review" FOREIGN KEY ("review_id") REFERENCES "booking_reviews"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_verification_events" ADD CONSTRAINT "FK_provider_verification_application" FOREIGN KEY ("application_id") REFERENCES "provider_applications"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_profiles" ADD CONSTRAINT "FK_provider_profiles_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_applications" ADD CONSTRAINT "fk_provider_applications_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_documents" ADD CONSTRAINT "FK_provider_documents_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_document_audit_events" ADD CONSTRAINT "FK_provider_document_audit_document" FOREIGN KEY ("document_id") REFERENCES "provider_documents"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_availability" ADD CONSTRAINT "FK_provider_availability_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_device_tokens" ADD CONSTRAINT "FK_push_device_tokens_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emergency_dispatches" ADD CONSTRAINT "FK_emergency_dispatches_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_messages" ADD CONSTRAINT "FK_booking_messages_sender" FOREIGN KEY ("sender_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_messages" ADD CONSTRAINT "FK_booking_messages_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_events" ADD CONSTRAINT "FK_booking_events_actor" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_events" ADD CONSTRAINT "FK_booking_events_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_calls" ADD CONSTRAINT "FK_booking_calls_callee" FOREIGN KEY ("callee_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_calls" ADD CONSTRAINT "FK_booking_calls_caller" FOREIGN KEY ("caller_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_calls" ADD CONSTRAINT "FK_booking_calls_booking" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_category" FOREIGN KEY ("service_category_id") REFERENCES "service_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_provider" FOREIGN KEY ("provider_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_bookings_customer" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_skills" ADD CONSTRAINT "FK_provider_skills_service_category" FOREIGN KEY ("service_category_id") REFERENCES "service_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "provider_skills" ADD CONSTRAINT "FK_provider_skills_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "otp_challenges" ADD CONSTRAINT "fk_otp_challenges_identity" FOREIGN KEY ("identity_id") REFERENCES "user_identities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ADD CONSTRAINT "fk_auth_sessions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_audit_events" ADD CONSTRAINT "fk_auth_audit_events_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
